<div id="anexoViewer" class="anexo-viewer d-none" role="dialog" aria-labelledby="anexoViewerTitulo"><div id="anexoViewerBarra" class="anexo-viewer-barra"><div class="d-flex gap-1"><button type="button" id="anexoViewerFechar" class="btn btn-sm btn-outline-light" title="Fechar"><i class="bi bi-x-lg"></i></button><button type="button" id="anexoViewerExpandir" class="btn btn-sm btn-outline-light" title="Maximizar"><i class="bi bi-arrows-fullscreen"></i></button><button type="button" id="anexoViewerZoomMenos" class="btn btn-sm btn-outline-light" title="Diminuir zoom" aria-label="Diminuir zoom"><i class="bi bi-zoom-out"></i></button><button type="button" id="anexoViewerZoomMais" class="btn btn-sm btn-outline-light" title="Aumentar zoom" aria-label="Aumentar zoom"><i class="bi bi-zoom-in"></i></button></div><div id="anexoViewerTitulo" class="anexo-viewer-titulo text-truncate"></div></div><div id="anexoViewerConteudo" class="anexo-viewer-conteudo"></div></div>
@once
@push('styles')<style>
.anexo-viewer{position:fixed;z-index:1080;left:10vw;top:10vh;width:80vw;height:80vh;min-width:320px;min-height:240px;background:#fff;border:1px solid #12355b;border-radius:.6rem;box-shadow:0 1rem 3rem rgba(0,0,0,.38);overflow:hidden;resize:both}.anexo-viewer.maximizado{inset:0!important;width:100vw!important;height:100vh!important;border-radius:0;resize:none}.anexo-viewer-barra{height:48px;padding:.45rem .65rem;display:flex;align-items:center;gap:.75rem;color:#fff;background:#12355b;cursor:move;user-select:none}.anexo-viewer-titulo{flex:1;text-align:center;font-weight:600;padding-right:5rem}.anexo-viewer-conteudo{height:calc(100% - 48px);overflow:auto;background:#e9ecef}.anexo-viewer-conteudo iframe{display:block;width:100%;height:100%;border:0;background:#fff}.anexo-viewer-conteudo img{display:block;min-width:100%;min-height:100%;object-fit:contain;background:#212529}
</style>@endpush
@push('scripts')<script>
document.addEventListener('DOMContentLoaded',()=>{const v=document.getElementById('anexoViewer');if(!v)return;const b=document.getElementById('anexoViewerBarra'),t=document.getElementById('anexoViewerTitulo'),c=document.getElementById('anexoViewerConteudo'),x=document.getElementById('anexoViewerExpandir');let d=false,ix=0,iy=0,il=0,it=0,zoom=100,url='',mime='',nome='';const aplicarZoom=()=>{const el=c.firstElementChild;if(!el)return;if(mime.startsWith('image/')){el.style.width=`${zoom}%`;el.style.minWidth='0';el.style.minHeight='0';el.style.margin='0 auto'}else{el.src=`${url.split('#')[0]}#zoom=${zoom}`}};const fechar=()=>{v.classList.add('d-none');c.replaceChildren()};document.getElementById('anexoViewerFechar').addEventListener('click',fechar);document.getElementById('anexoViewerZoomMenos').addEventListener('click',()=>{zoom=Math.max(25,zoom-25);aplicarZoom()});document.getElementById('anexoViewerZoomMais').addEventListener('click',()=>{zoom=Math.min(300,zoom+25);aplicarZoom()});x.addEventListener('click',()=>{const m=v.classList.toggle('maximizado');x.querySelector('i').className=m?'bi bi-fullscreen-exit':'bi bi-arrows-fullscreen';x.title=m?'Restaurar':'Maximizar'});document.querySelectorAll('.abrir-anexo-viewer').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();url=a.href;mime=a.dataset.mime;nome=a.dataset.nome;zoom=100;t.textContent=`${nome} - ${a.dataset.colaborador}`;c.replaceChildren();const el=document.createElement(mime.startsWith('image/')?'img':'iframe');el.src=url;el.title=nome;el.alt=nome;c.appendChild(el);v.classList.remove('d-none')}));b.addEventListener('mousedown',e=>{if(e.target.closest('button')||v.classList.contains('maximizado'))return;d=true;ix=e.clientX;iy=e.clientY;il=v.offsetLeft;it=v.offsetTop});document.addEventListener('mousemove',e=>{if(!d)return;v.style.left=`${Math.max(0,Math.min(innerWidth-v.offsetWidth,il+e.clientX-ix))}px`;v.style.top=`${Math.max(0,Math.min(innerHeight-48,it+e.clientY-iy))}px`});document.addEventListener('mouseup',()=>d=false);document.addEventListener('keydown',e=>{if(e.key==='Escape')fechar()})});
</script>@endpush
@endonce
