@extends('layouts.app')
@php($editando=$responsavel->exists)
@section('title',($editando?'Editar':'Cadastrar').' responsável')
@push('styles')<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" rel="stylesheet">@endpush
@section('content')
<div class="page-header"><div><h1 class="page-title">{{ $editando?'Editar':'Cadastrar' }} responsável</h1><p class="page-description">Informe o colaborador, o cargo e os setores sob sua responsabilidade.</p></div></div><form method="POST" action="{{ $editando?route('responsaveis.update',$responsavel):route('responsaveis.store') }}">@csrf @if($editando) @method('PUT') @endif<div class="card content-card"><div class="card-header"><h5>Dados do responsável</h5></div><div class="card-body">@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $erro)<li>{{ $erro }}</li>@endforeach</ul></div>@endif<div class="row g-3">
<div class="col-md-6"><label for="cargo" class="form-label">Cargo <span class="text-danger">*</span></label><input id="cargo" name="cargo" maxlength="255" required class="form-control" value="{{ old('cargo',$responsavel->cargo) }}"></div>
<div class="col-12"><label for="colaborador_id" class="form-label">Colaborador <span class="text-danger">*</span></label><select id="colaborador_id" name="colaborador_id" class="form-select @error('colaborador_id') is-invalid @enderror" required><option value=""></option>@if($colaboradorSelecionado)<option value="{{ $colaboradorSelecionado->id }}" selected>{{ $colaboradorSelecionado->nome }} - {{ $colaboradorSelecionado->email }}</option>@endif</select>@error('colaborador_id')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
<div class="col-12"><label for="setores" class="form-label">Setores <span class="text-danger">*</span></label><select id="setores" name="setores[]" class="form-select @error('setores') is-invalid @enderror" multiple required>@foreach($setores as $setor)<option value="{{ $setor->id }}" @selected(in_array($setor->id,old('setores',$responsavel->setores->pluck('id')->all())))>{{ $setor->nome }}</option>@endforeach</select>@error('setores')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
</div><div class="d-flex justify-content-end gap-2 mt-4">@if($giPermissoes->permite('responsaveis.listar'))<a href="{{ route('responsaveis.index') }}" class="btn btn-outline-secondary">Cancelar</a>@endif<button class="btn btn-primary"><i class="bi bi-check-lg me-1"></i>Salvar</button></div></div></div></form>
@endsection
@push('scripts')<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script><script>document.addEventListener('DOMContentLoaded',()=>{$('#colaborador_id').select2({theme:'bootstrap-5',placeholder:'Pesquise pelo nome ou e-mail',minimumInputLength:1,width:'100%',ajax:{url:'{{ route('responsaveis.colaboradores.search') }}',dataType:'json',delay:300,data:p=>({q:p.term}),processResults:d=>d,cache:true}});$('#setores').select2({theme:'bootstrap-5',placeholder:'Selecione um ou mais setores',width:'100%'});});</script>@endpush
