@extends('layouts.app')
@php($editando = $grupo->exists)
@section('title', ($editando ? 'Editar' : 'Cadastrar').' grupo CID-10')
@section('content')
<div class="page-header"><div><h1 class="page-title">{{ $editando ? 'Editar' : 'Cadastrar' }} grupo CID-10</h1><p class="page-description">Informe os dados do grupo.</p></div></div>
<form method="POST" action="{{ $editando ? route('cid10_grupos.update', $grupo) : route('cid10_grupos.store') }}">@csrf @if($editando) @method('PUT') @endif<div class="card content-card"><div class="card-header"><h5>Dados do grupo</h5></div><div class="card-body">@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $erro)<li>{{ $erro }}</li>@endforeach</ul></div>@endif<div class="row g-3">
<div class="col-12"><label for="titulo" class="form-label">Título <span class="text-danger">*</span></label><textarea id="titulo" name="titulo" rows="3" class="form-control @error('titulo') is-invalid @enderror" required>{{ old('titulo', $grupo->titulo) }}</textarea>@error('titulo')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-3"><label for="cod_grupo" class="form-label">Código do grupo</label><input type="number" id="cod_grupo" name="cod_grupo" class="form-control" value="{{ old('cod_grupo', $grupo->cod_grupo) }}"></div><div class="col-md-3"><label for="catinic" class="form-label">Categoria inicial</label><input id="catinic" name="catinic" maxlength="255" class="form-control" value="{{ old('catinic', $grupo->catinic) }}"></div><div class="col-md-3"><label for="catfim" class="form-label">Categoria final</label><input id="catfim" name="catfim" maxlength="255" class="form-control" value="{{ old('catfim', $grupo->catfim) }}"></div><div class="col-md-3"><label for="ativo" class="form-label">Situação <span class="text-danger">*</span></label><select id="ativo" name="ativo" class="form-select" required><option value="1" @selected((string)old('ativo',(int)($grupo->ativo ?? true))==='1')>Ativo</option><option value="0" @selected((string)old('ativo',(int)($grupo->ativo ?? true))==='0')>Inativo</option></select></div>
<div class="col-md-6"><label for="descricao" class="form-label">Descrição</label><input id="descricao" name="descricao" maxlength="255" class="form-control" value="{{ old('descricao', $grupo->descricao) }}"></div><div class="col-md-6"><label for="descrabrev" class="form-label">Descrição abreviada</label><input id="descrabrev" name="descrabrev" maxlength="255" class="form-control" value="{{ old('descrabrev', $grupo->descrabrev) }}"></div>
</div><div class="d-flex justify-content-end gap-2 mt-4">@if($giPermissoes->permite('cid10_grupos.listar'))<a href="{{ route('cid10_grupos.index') }}" class="btn btn-outline-secondary">Cancelar</a>@endif<button class="btn btn-primary"><i class="bi bi-check-lg me-1"></i>Salvar</button></div></div></div></form>
@endsection
