@extends('layouts.app')
@php($editando = $subcategoria->exists)
@section('title', ($editando ? 'Editar' : 'Cadastrar').' subcategoria CID-10')
@section('content')
<div class="page-header"><div><h1 class="page-title">{{ $editando ? 'Editar' : 'Cadastrar' }} subcategoria CID-10</h1><p class="page-description">Informe os dados da subcategoria.</p></div></div>
<form method="POST" action="{{ $editando ? route('cid10_subcategorias.update', $subcategoria) : route('cid10_subcategorias.store') }}">@csrf @if($editando) @method('PUT') @endif<div class="card content-card"><div class="card-header"><h5>Dados da subcategoria</h5></div><div class="card-body">@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $erro)<li>{{ $erro }}</li>@endforeach</ul></div>@endif<div class="row g-3">
<div class="col-md-3"><label for="subcat" class="form-label">Subcategoria</label><input id="subcat" name="subcat" maxlength="4" class="form-control" value="{{ old('subcat', $subcategoria->subcat) }}"></div><div class="col-md-6"><label for="classif" class="form-label">Classificação</label><input id="classif" name="classif" maxlength="255" class="form-control" value="{{ old('classif', $subcategoria->classif) }}"></div><div class="col-md-3"><label for="ativo" class="form-label">Situação <span class="text-danger">*</span></label><select id="ativo" name="ativo" class="form-select" required><option value="1" @selected((string)old('ativo',(int)($subcategoria->ativo ?? true))==='1')>Ativa</option><option value="0" @selected((string)old('ativo',(int)($subcategoria->ativo ?? true))==='0')>Inativa</option></select></div>
<div class="col-md-6"><label for="restrsexo" class="form-label">Restrição de sexo</label><input id="restrsexo" name="restrsexo" maxlength="255" class="form-control" value="{{ old('restrsexo', $subcategoria->restrsexo) }}"></div><div class="col-md-6"><label for="causaobito" class="form-label">Causa de óbito</label><input id="causaobito" name="causaobito" maxlength="255" class="form-control" value="{{ old('causaobito', $subcategoria->causaobito) }}"></div><div class="col-md-6"><label for="descricao" class="form-label">Descrição</label><input id="descricao" name="descricao" maxlength="262" class="form-control" value="{{ old('descricao', $subcategoria->descricao) }}"></div><div class="col-md-6"><label for="descrabrev" class="form-label">Descrição abreviada</label><input id="descrabrev" name="descrabrev" maxlength="255" class="form-control" value="{{ old('descrabrev', $subcategoria->descrabrev) }}"></div><div class="col-md-6"><label for="refer" class="form-label">Referência</label><input id="refer" name="refer" maxlength="255" class="form-control" value="{{ old('refer', $subcategoria->refer) }}"></div><div class="col-md-6"><label for="excluidos" class="form-label">Excluídos</label><input id="excluidos" name="excluidos" maxlength="255" class="form-control" value="{{ old('excluidos', $subcategoria->excluidos) }}"></div>
</div><div class="d-flex justify-content-end gap-2 mt-4">@if($giPermissoes->permite('cid10_subcategorias.listar'))<a href="{{ route('cid10_subcategorias.index') }}" class="btn btn-outline-secondary">Cancelar</a>@endif<button class="btn btn-primary"><i class="bi bi-check-lg me-1"></i>Salvar</button></div></div></div></form>
@endsection
