@extends('layouts.app')
@php($editando = $categoriaCid->exists)
@section('title', ($editando ? 'Editar' : 'Cadastrar').' categoria CID-10')
@section('content')
<div class="page-header"><div><h1 class="page-title">{{ $editando ? 'Editar' : 'Cadastrar' }} categoria CID-10</h1><p class="page-description">Informe os dados da categoria.</p></div></div>
<form method="POST" action="{{ $editando ? route('cid10_categorias.update', $categoriaCid) : route('cid10_categorias.store') }}">@csrf @if($editando) @method('PUT') @endif<div class="card content-card"><div class="card-header"><h5>Dados da categoria</h5></div><div class="card-body">@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $erro)<li>{{ $erro }}</li>@endforeach</ul></div>@endif<div class="row g-3">
<div class="col-md-3"><label for="cat" class="form-label">Categoria</label><input id="cat" name="cat" maxlength="3" class="form-control" value="{{ old('cat', $categoriaCid->cat) }}"></div><div class="col-md-6"><label for="classif" class="form-label">Classificação</label><input id="classif" name="classif" maxlength="255" class="form-control" value="{{ old('classif', $categoriaCid->classif) }}"></div><div class="col-md-3"><label for="ativo" class="form-label">Situação <span class="text-danger">*</span></label><select id="ativo" name="ativo" class="form-select" required><option value="1" @selected((string)old('ativo',(int)($categoriaCid->ativo ?? true))==='1')>Ativa</option><option value="0" @selected((string)old('ativo',(int)($categoriaCid->ativo ?? true))==='0')>Inativa</option></select></div>
<div class="col-md-6"><label for="descricao" class="form-label">Descrição</label><input id="descricao" name="descricao" maxlength="255" class="form-control" value="{{ old('descricao', $categoriaCid->descricao) }}"></div><div class="col-md-6"><label for="descrabrev" class="form-label">Descrição abreviada</label><input id="descrabrev" name="descrabrev" maxlength="255" class="form-control" value="{{ old('descrabrev', $categoriaCid->descrabrev) }}"></div><div class="col-md-6"><label for="refer" class="form-label">Referência</label><input id="refer" name="refer" maxlength="255" class="form-control" value="{{ old('refer', $categoriaCid->refer) }}"></div><div class="col-md-6"><label for="excluidos" class="form-label">Excluídos</label><input id="excluidos" name="excluidos" maxlength="255" class="form-control" value="{{ old('excluidos', $categoriaCid->excluidos) }}"></div>
</div><div class="d-flex justify-content-end gap-2 mt-4">@if($giPermissoes->permite('cid10_categorias.listar'))<a href="{{ route('cid10_categorias.index') }}" class="btn btn-outline-secondary">Cancelar</a>@endif<button class="btn btn-primary"><i class="bi bi-check-lg me-1"></i>Salvar</button></div></div></div></form>
@endsection
