@extends('layouts.app')
@php($editando = isset($justificativa))
@section('title', $editando ? 'Editar justificativa' : 'Cadastrar justificativa')
@push('styles')<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" rel="stylesheet">@endpush

@section('content')
<div class="page-header"><div><h1 class="page-title">{{ $editando ? 'Editar' : 'Cadastrar' }} justificativa</h1><p class="page-description">Informe os dados e os documentos comprobatórios.</p></div></div>
<form method="POST" action="{{ $editando ? route('justificativas.update', $justificativa) : route('justificativas.store') }}" enctype="multipart/form-data">@csrf @if($editando) @method('PUT') @endif
<div class="card content-card"><div class="card-header"><h5>Dados da justificativa</h5></div><div class="card-body">
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $erro)<li>{{ $erro }}</li>@endforeach</ul></div>@endif
<div class="row g-3">
<div class="col-12"><label for="descricao" class="form-label">Descrição <span class="text-danger">*</span></label><textarea id="descricao" name="descricao" rows="5" class="form-control @error('descricao') is-invalid @enderror" required autofocus>{{ old('descricao', $justificativa->descricao ?? '') }}</textarea></div>
<div class="col-md-6"><label for="colaborador" class="form-label">Colaborador <span class="text-danger">*</span></label><input id="colaborador" class="form-control" value="{{ $colaborador->nome }}" disabled></div>
<div class="col-md-6"><label for="categoria_id" class="form-label">Categoria <span class="text-danger">*</span></label><select id="categoria_id" name="categoria_id" class="form-select" required><option value="">Selecione</option>@foreach($categorias as $categoria)<option value="{{ $categoria->id }}" @selected((string)old('categoria_id', $justificativa->categoria_id ?? '')===(string)$categoria->id)>{{ $categoria->nome }}</option>@endforeach</select></div>

<div class="col-12"><div class="form-label">Anexos @unless($editando)<span class="text-danger">*</span>@endunless</div><div class="form-text mb-2">PDF, JPG, PNG ou WebP, com até 10 MB por arquivo.</div>
<input type="file" id="anexos" name="anexos[]" class="visually-hidden" accept="application/pdf,image/jpeg,image/png,image/webp" multiple @required(!$editando)>
<div id="anexosGrid" class="row g-3">
@if($editando)
@foreach($justificativa->anexos as $anexo)
<div class="col-6 col-md-4 col-lg-3 anexo-card" data-persistido="true"><div class="card h-100 position-relative">@if($giPermissoes->permite('justificativa.anexos.excluir'))<button type="button" class="btn btn-sm btn-danger position-absolute top-0 end-0 m-2 excluir-anexo" style="z-index:2" data-url="{{ route('justificativas.anexos.destroy', [$justificativa, $anexo]) }}" title="Excluir anexo" aria-label="Excluir {{ $anexo->nome_original }}"><i class="bi bi-trash-fill"></i></button>@endif
@if($giPermissoes->permite('justificativa.anexos.visualizar'))<a href="{{ route('justificativas.anexo', [$justificativa, $anexo]) }}" target="_blank">@if(str_starts_with($anexo->mime, 'image/'))<img src="{{ route('justificativas.anexo', [$justificativa, $anexo]) }}" class="card-img-top object-fit-cover" style="height:150px" alt="{{ $anexo->nome_original }}">@else<div class="d-flex align-items-center justify-content-center bg-light text-danger" style="height:150px"><i class="bi bi-file-earmark-pdf-fill" style="font-size:4rem"></i></div>@endif</a>@else<div class="d-flex align-items-center justify-content-center bg-light text-secondary" style="height:150px"><i class="bi bi-paperclip" style="font-size:3rem"></i></div>@endif
<div class="card-body p-2 small text-truncate" title="{{ $anexo->nome_original }}">{{ $anexo->nome_original }}</div></div></div>
@endforeach
@endif
<div id="adicionarAnexoCard" class="col-6 col-md-4 col-lg-3"><button type="button" id="adicionarAnexo" class="card h-100 w-100 border-2 border-dashed bg-body-tertiary text-primary" style="min-height:190px"><span class="d-flex flex-column align-items-center justify-content-center"><i class="bi bi-plus-circle" style="font-size:3rem"></i><span class="fw-semibold mt-2">Adicionar anexo</span></span></button></div>
</div></div>

<div class="col-md-6"><label for="atestado_medico" class="form-label">Este anexo é um atestado médico de tratamento de saúde? <span class="text-danger">*</span></label><select id="atestado_medico" name="atestado_medico" class="form-select" required><option value="">Selecione</option><option value="1" @selected((string)old('atestado_medico',isset($justificativa)?(int)$justificativa->atestado_medico:'')==='1')>Sim</option><option value="0" @selected((string)old('atestado_medico',isset($justificativa)?(int)$justificativa->atestado_medico:'')==='0')>Não</option></select></div>
<div id="dadosMedicoBloco" class="col-12 d-none"><div class="row g-3"><div class="col-md-6"><label for="crm_medico" class="form-label">CRM médico(a) <span class="text-danger">*</span></label><input id="crm_medico" name="crm_medico" maxlength="15" class="form-control @error('crm_medico') is-invalid @enderror" value="{{ old('crm_medico', $justificativa->crm_medico ?? '') }}">@error('crm_medico')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label for="cid" class="form-label">CID <span class="text-muted fw-normal">(opcional)</span></label><select id="cid" name="cid" class="form-select @error('cid') is-invalid @enderror"><option value=""></option>@if($cidSelecionado)<option value="{{ $cidSelecionado->subcat }}" selected>{{ $cidSelecionado->subcat }} - {{ $cidSelecionado->descricao }}</option>@endif</select>@error('cid')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div></div>
<div id="tipoAtestadoBloco" class="col-12 d-none"><fieldset><legend class="form-label fs-6">É um atestado próprio ou de acompanhamento de familiar? <span class="text-danger">*</span></legend><div class="d-flex gap-4"><div class="form-check"><input class="form-check-input" type="radio" name="tipo_atestado" id="tipo_proprio" value="proprio" @checked(old('tipo_atestado',$justificativa->tipo_atestado??null)==='proprio')><label for="tipo_proprio">Atestado próprio</label></div><div class="form-check"><input class="form-check-input" type="radio" name="tipo_atestado" id="tipo_acompanhamento" value="acompanhamento" @checked(old('tipo_atestado',$justificativa->tipo_atestado??null)==='acompanhamento')><label for="tipo_acompanhamento">Acompanhamento de familiar</label></div></div></fieldset></div>
<div id="parentescoBloco" class="col-md-6 d-none"><label for="grau_parentesco_id" class="form-label">Grau de parentesco <span class="text-danger">*</span></label><select id="grau_parentesco_id" name="grau_parentesco_id" class="form-select"><option value="">Selecione</option>@foreach($grausParentesco as $grau)<option value="{{ $grau->id }}" @selected((string)old('grau_parentesco_id',$justificativa->grau_parentesco_id??'')===(string)$grau->id)>{{ $grau->nome }}</option>@endforeach</select></div>
</div><div class="d-flex justify-content-end gap-2 mt-4"><a href="{{ route('justificativas.index') }}" class="btn btn-outline-secondary">Cancelar</a><button class="btn btn-primary"><i class="bi bi-check-lg me-1"></i>Salvar</button></div></div></div></form>
@endsection

@push('scripts')
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
document.addEventListener('DOMContentLoaded', () => {
    $('#cid').select2({theme:'bootstrap-5',placeholder:'Pesquise pelo código ou descrição',allowClear:true,width:'100%',minimumInputLength:1,ajax:{url:'{{ route('justificativas.cids.search') }}',dataType:'json',delay:300,data:params=>({q:params.term}),processResults:data=>data,cache:true}});
    const atestado = document.getElementById('atestado_medico'), dadosMedicoBloco = document.getElementById('dadosMedicoBloco'), crmMedico = document.getElementById('crm_medico'), cid = document.getElementById('cid'), tipoBloco = document.getElementById('tipoAtestadoBloco'), parentescoBloco = document.getElementById('parentescoBloco'), parentesco = document.getElementById('grau_parentesco_id'), tipos = [...document.querySelectorAll('input[name="tipo_atestado"]')];
    const atualizar = () => { const sim = atestado.value === '1', acompanhamento = document.getElementById('tipo_acompanhamento').checked; dadosMedicoBloco.classList.toggle('d-none', !sim); crmMedico.required = sim; tipoBloco.classList.toggle('d-none', !sim); parentescoBloco.classList.toggle('d-none', !sim || !acompanhamento); tipos.forEach(tipo => tipo.required = sim); parentesco.required = sim && acompanhamento; if (!sim) { crmMedico.value = ''; $('#cid').val(null).trigger('change'); tipos.forEach(tipo => tipo.checked = false); } if (!sim || !acompanhamento) parentesco.value = ''; };
    atestado.addEventListener('change', atualizar); tipos.forEach(tipo => tipo.addEventListener('change', atualizar)); atualizar();

    const input = document.getElementById('anexos'), adicionarCard = document.getElementById('adicionarAnexoCard');
    let arquivos = [];
    const sincronizarInput = () => { const transferencia = new DataTransfer(); arquivos.forEach(({ arquivo }) => transferencia.items.add(arquivo)); input.files = transferencia.files; };
    const criarCard = (item) => { const coluna = document.createElement('div'); coluna.className = 'col-6 col-md-4 col-lg-3 anexo-card'; coluna.dataset.chave = item.chave; const visual = item.arquivo.type.startsWith('image/') ? `<img src="${URL.createObjectURL(item.arquivo)}" class="card-img-top object-fit-cover" style="height:150px" alt="">` : '<div class="d-flex align-items-center justify-content-center bg-light text-danger" style="height:150px"><i class="bi bi-file-earmark-pdf-fill" style="font-size:4rem"></i></div>'; coluna.innerHTML = `<div class="card h-100 position-relative"><button type="button" class="btn btn-sm btn-danger position-absolute top-0 end-0 m-2 excluir-novo" style="z-index:2" title="Excluir anexo"><i class="bi bi-trash-fill"></i></button>${visual}<div class="card-body p-2 small text-truncate"></div></div>`; coluna.querySelector('.card-body').textContent = item.arquivo.name; coluna.querySelector('.excluir-novo').addEventListener('click', () => { if (!confirm('Tem certeza que deseja excluir este anexo?')) return; arquivos = arquivos.filter(arquivo => arquivo.chave !== item.chave); sincronizarInput(); coluna.remove(); }); adicionarCard.before(coluna); };
    document.getElementById('adicionarAnexo').addEventListener('click', () => input.click());
    input.addEventListener('change', () => { [...input.files].forEach(arquivo => { const item = { arquivo, chave: crypto.randomUUID() }; arquivos.push(item); criarCard(item); }); sincronizarInput(); });

    document.querySelectorAll('.excluir-anexo').forEach(botao => botao.addEventListener('click', async () => { if (!confirm('Tem certeza que deseja excluir este anexo?')) return; botao.disabled = true; try { const resposta = await fetch(botao.dataset.url, { method: 'DELETE', headers: { 'X-CSRF-TOKEN': @json(csrf_token()), 'Accept': 'application/json' } }); if (!resposta.ok) throw new Error(); botao.closest('.anexo-card').remove(); } catch { alert('Não foi possível excluir o anexo.'); botao.disabled = false; } }));
});
</script>
@endpush
